again/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    re_path (r'^$', views.index, name='index'),
    re_path (r'^album/$', views.AlbumListView.as_view(), name='album'),
    re_path (r'^albums/(?P<pk>\d+)$', views.AlbumDetailView.as_view(), name='album-detail'),
    re_path (r'^author/$', views.AuthorListView.as_view(), name='author'),
    re_path (r'^authors/(?P<pk>\d+)$', views.AuthorDetailView.as_view(), name='author-detail'),
    
]
urlpatterns += [
    re_path('author/create/', views.AuthorCreate.as_view(), name='author-create'),
    re_path('author/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author-update'),
    re_path('author/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author-delete'),
]
urlpatterns += [
    re_path('album/create/', views.AlbumCreate.as_view(), name='album-create'),
    re_path('album/<int:pk>/update/', views.AlbumUpdate.as_view(), name='album-update'),
    re_path('album/<int:pk>/delete/', views.AlbumDelete.as_view(), name='album-delete'),
]

local/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [   
path('admin/', admin.site.urls),
path('again/', include('again.urls')),
path('', RedirectView.as_view(url='/again/', permanent=True)), 
#path('accounts/', include('django.contrib.auth.urls')),
path('users/', include('users.urls', namespace="users")),
] +static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView, PasswordChangeView, PasswordChangeDoneView
app_name = "users"

urlpatterns = [
    path('profile/profile-update/', views.ProfileUser.as_view(template_name="users/profile_update.html"), name='profile_update'),
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('login/', views.LoginUser.as_view(), name='login'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),
    path('password-change/', views.UserPasswordChange.as_view(template_name="users/password_change_form.html"), name="password_change"),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"), name="password_change_done"),
]

again/models.py
from django.db import models
from django.contrib.auth import get_user_model
# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=200, help_text="Enter a book genre (e.g. Science Fiction, French Poetry etc.)")

    def __str__(self):
        return self.name

from django.urls import reverse #Used to generate URLs by reversing the URL patterns

class Album(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    genre = models.ManyToManyField(Genre, help_text="Select a genre for this album")
    writer = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, related_name='posts', null=True, default=None)


    def __str__(self):
        return self.title


    def get_absolute_url(self):
        return reverse('album-detail', args=[str(self.id)])

class Author(models.Model):

    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)

    def get_absolute_url(self):

        return reverse('author-detail', args=[str(self.id)])


    def __str__(self):

        return '%s %s' % (self.first_name, self.last_name)

again/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Album, Author, Genre

def index(request):
    """
    Функция отображения для домашней страницы сайта.
    """
    # Генерация "количеств" некоторых главных объектов
    num_albums=Album.objects.all().count()
    num_authors=Author.objects.count()  # Метод 'all()' применён по умолчанию.
    num_visits=request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits+1


    return render(
        request,
        'index.html',
        context={'num_albums':num_albums,'num_authors':num_authors,'num_visits':num_visits },
    )



# def profile(request):
#    albums=Album.objects.filter(writer=request.user)
#    author=Author.objects.all()
#    #writer=User.object.all()
#    return render(
#        request,
#        'again/profile.html',
#        context={albums:'albums',author:'author'},)


class AlbumListView(generic.ListView):
    model = Album
    context_object_name = 'my_album_list'   # ваше собственное имя переменной контекста в шаблоне
    template_name = 'again/albumList.html'  # Определение имени вашего шаблона и его расположения

    def get_context_data(self, **kwargs):
        # В первую очередь получаем базовую реализацию контекста
        context = super(AlbumListView, self).get_context_data(**kwargs)
        # Добавляем новую переменную к контексту и инициализируем её некоторым значением
        context['some_data'] = 'This is just some data'
        return context

class AlbumDetailView(LoginRequiredMixin,generic.DetailView):
    model = Album
    template_name = 'again/albumDetail.html'  # Определение имени вашего шаблона и его расположения
    login_url = '/users/login/'
    
def album_detail_view(request,pk):
    try:
        album_id=Album.objects.get(pk=pk)
    except Album.DoesNotExist:
        raise Http404("Album does not exist")

    #book_id=get_object_or_404(Book, pk=pk)

    return render(
        request,
        'again/albumDetail.html',
        context={'album':album_id,}
    )



class AuthorListView(generic.ListView):
    model = Author
    context_object_name = 'my_author_list'   # ваше собственное имя переменной контекста в шаблоне
    template_name = 'again/authorList.html'  # Определение имени вашего шаблона и его расположения

    def get_context_data(self, **kwargs):
        # В первую очередь получаем базовую реализацию контекста
        context = super(AuthorListView, self).get_context_data(**kwargs)
        # Добавляем новую переменную к контексту и инициализируем её некоторым значением
        context['Album'] = Album.objects.all()
        return context

class AuthorDetailView(LoginRequiredMixin,generic.DetailView):
    model = Author
    template_name = 'again/authorDetail.html'  # Определение имени вашего шаблона и его расположения
    login_url = '/users/login/'
    
def author_detail_view(request,pk):
    try:
        author_id=Author.objects.get(pk=pk)
    except Author.DoesNotExist:
        raise Http404("Author does not exist")

    #book_id=get_object_or_404(Book, pk=pk)

    return render(
        request,
        'again/authorDetail.html',
        context={'author':author_id,}
    )




class AuthorCreate(CreateView):
    model = Author
    fields = '__all__'

class AuthorUpdate(UpdateView):
    model = Author
    fields = ['first_name','last_name']




class AuthorDelete(DeleteView):
    model = Author
    success_url = reverse_lazy('author')

    
    def form_valid(self, form):
        try:
            self.object.delete()
            return HttpResponseRedirect(self.success_url)
        except Exception as e:
            return HttpResponseRedirect(
                reverse("author-delete", kwargs={"pk": self.object.pk})
            )




class AlbumCreate(CreateView):
    model = Album
    fields = '__all__'
    def form_valid(self, form):
        w = form.save(commit=False)
        w.writer = self.request.user
        return super().form_valid(form)






class AlbumUpdate(UpdateView):
    model = Album
    fields = ['title','genre']
    def form_valid(self, form):
        try:
            self.object.update()
            return HttpResponseRedirect(self.success_url)
        except Exception as e:
            return HttpResponseRedirect(
                reverse("album-update", kwargs={"pk": self.object.pk})
            )
    


class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('album')
    def form_valid(self, form):
        try:
            self.object.delete()
            return HttpResponseRedirect(self.success_url)
        except Exception as e:
            return HttpResponseRedirect(
                reverse("album-delete", kwargs={"pk": self.object.pk})
            )

again/templates/again/albumDetail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Название альбома: {{ album.title }}</h1>

  <p><strong>Исполнитель:</strong> <a href="{{ album.author.get_absolute_url }}">{{ album.author }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>Жанр:</strong> {% for genre in album.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>
  <ul class="sidebar-nav">
<p class="first"> Редактор: {{album.writer.username|default:"неизвестен"}}</p>
  <div style="margin-left:20px;margin-top:20px">
  </div>
{% endblock %}

again/templates/again/albumList.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Вся библиография</h1>
    <ul class="sidebar-nav">

      {% if user.is_authenticated %}
        <li><a href="{% url 'album-create' %}">Добавить альбом</li>
      {% else %}
        <li><a href="{% url 'users:login'%}?next={{request.path}}">Войдите,чтобы добавить альбом </a></li>
      {% endif %}
     </ul>
    {% if my_album_list %}
    <ul>

      {% for album in my_album_list %}
      <li>
        <a href="{{ album.get_absolute_url }}">{{ album.title }}</a> ({{album.author}})
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no album in the library.</p>
    {% endif %}
{% endblock %}

again/templates/again/album_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Album</h1>

<p>Are you sure you want to delete the author: {{ author }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete." />
</form>

{% endblock %}

again/templates/again/album_form.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />

</form>
{% endblock %}

again/templates/again/authorDetail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Исполнитель: {{ author.first_name}} {{author.last_name }}</h1>

  <ul class="sidebar-nav">

    {% if user.is_authenticated %}
      <li><a href="{% url 'album-create' %}">Добавить альбом</li></a>

    {% else %}
      <li><a href="{% url 'users.login'%}?next={{request.path}}">Войдите,чтобы добавить альбом </a></li>
    {% endif %}
  </ul>


<strong>Альбомы:</strong>

  {% for album in author.album_set.all %}  <li> <a href="{{ album.get_absolute_url }}"> {{ album }}  </a></li> {% endfor %}
  
  <div style="margin-left:20px;margin-top:20px">
  </div>
{% endblock %}

again/templates/again/authorList.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Список исполнителей</h1>
    <ul class="sidebar-nav">

      {% if user.is_authenticated %}
        <li><a href="{% url 'author-create' %}">Добавить исполнителя</li>
      {% else %}
        <li><a href="{% url 'users:login'%}?next={{request.path}}">Войдите,чтобы добавить исполнителя </a></li>
      {% endif %}
     </ul>

    {% if my_author_list %}
    <ul>

      {% for author in my_author_list %}
      <li>
        <a href="{{ author.get_absolute_url }}">{{ author.first_name}} {{author.last_name }}</a>
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no album in the library.</p>
    {% endif %}
{% endblock %}

again/templates/again/author_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Author</h1>

<p>Are you sure you want to delete the author: {{ author }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete." />
</form>

{% endblock %}

again/templates/again/author_form.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />

</form>
{% endblock %}