again/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    re_path (r'^$', views.index, name='index'),
    re_path (r'^album/$', views.AlbumListView.as_view(), name='album'),
    re_path (r'^albums/(?P<pk>\d+)$', views.AlbumDetailView.as_view(), name='album-detail'),
    re_path (r'^author/$', views.AuthorListView.as_view(), name='author'),
    re_path (r'^authors/(?P<pk>\d+)$', views.AuthorDetailView.as_view(), name='author-detail'),
    
]
urlpatterns += [
    re_path('author/create/', views.AuthorCreate.as_view(), name='author-create'),
    re_path('author/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author-update'),
    re_path('author/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author-delete'),
]
urlpatterns += [
    re_path('album/create/', views.AlbumCreate.as_view(), name='album-create'),
    re_path('album/<int:pk>/update/', views.AlbumUpdate.as_view(), name='album-update'),
    re_path('album/<int:pk>/delete/', views.AlbumDelete.as_view(), name='album-delete'),
]

local/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [   
path('admin/', admin.site.urls),
path('again/', include('again.urls')),
path('', RedirectView.as_view(url='/again/', permanent=True)), 
#path('accounts/', include('django.contrib.auth.urls')),
path('users/', include('users.urls', namespace="users")),
] +static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView, PasswordChangeView, PasswordChangeDoneView
app_name = "users"

urlpatterns = [
    path('profile/profile-update/', views.ProfileUser.as_view(template_name="users/profile_update.html"), name='profile_update'),
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('login/', views.LoginUser.as_view(), name='login'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),
    path('password-change/', views.UserPasswordChange.as_view(template_name="users/password_change_form.html"), name="password_change"),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"), name="password_change_done"),
]

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm,UserCreationForm
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy
from . import models
from django.contrib.auth.forms import PasswordChangeForm


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label='Повтор пароля', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']
        labels = {
            'email': 'E-mail',
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }
        widgets = {
            'email': forms.TextInput(attrs={'class': 'form-input'}),
            'first_name': forms.TextInput(attrs={'class': 'form-input'}),
            'last_name': forms.TextInput(attrs={'class': 'form-input'}),
        }
 
    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError("Такой E-mail уже существует!")
        return email

class ProfileUserForm(forms.ModelForm):
    username = forms.CharField(disabled=True, label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.CharField(disabled=True, label='E-mail', widget=forms.TextInput(attrs={'class': 'form-input'}))
 
    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name']
        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-input'}),
            'last_name': forms.TextInput(attrs={'class': 'form-input'}),
        }

class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label="Старый пароль", widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password1 = forms.CharField(label="Новый пароль", widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password2 = forms.CharField(label="Подтверждение пароля", widget=forms.PasswordInput(attrs={'class': 'form-input'}))

users/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.contrib.auth import authenticate,login,logout
from users.forms import ProfileUserForm, RegisterUserForm, UserPasswordChangeForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import LoginView,PasswordChangeView
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model


# Create your views here.
class LoginUser(LoginView):
    form_class = AuthenticationForm
    template_name = 'users/login.html'
    extra_context = {'title': "Авторизация"}
    login_url = '/users/profile/'

def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('users:login'))

class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = 'users/register.html'
    extra_context = {'title': "Регистрация"}
    success_url = reverse_lazy('users:login')
class ProfileUser(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = ProfileUserForm
    template_name = 'users/profile.html'
    extra_context = {'title': "Профиль пользователя"}
    success_url = reverse_lazy('profile')
 
    def get_success_url(self):
        return reverse_lazy('users:profile', args=[self.request.user.pk])
        
    def get_object(self, queryset=None):
        return self.request.user

    def form_valid(self, form):
        try:
            self.object.update()
            return HttpResponseRedirect(self.success_url)
        except Exception as e:
            return HttpResponseRedirect(
                reverse("profile_update", kwargs={"pk": self.object.pk})
            )
    
class UserPasswordChange(PasswordChangeView):
    form_class = UserPasswordChangeForm
    success_url = reverse_lazy("users:password_change_done")
    extra_context = {'title': "Изменение пароля"}

    def form_valid(self, form):
        try:
            self.object.update()
            return HttpResponseRedirect(self.success_url)
        except Exception as e:
            return HttpResponseRedirect(
                reverse("profile_update", kwargs={"pk": self.object.pk})
            )

users/templates/users/login.html
{% extends 'base_generic.html' %}
 
{% block content %}
<h1>Авторизация</h1>

<form method="post">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}" />
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <p><button type="submit">Войти</button></p>
</form>
{% endblock %}

users/templates/users/password_change_done.html
{% extends 'base_generic.html' %}
 
{% block content %}
<h1>Пароль успешно изменен!</h1>
 
<p >Вы успешно изменили пароль. <a href="{% url 'users:profile' %}">Вернуться в профиль.</a></p>
{% endblock %}

users/templates/users/password_change_form.html
{% extends 'base_generic.html' %}
 
{% block content %}
<h1>Изменение пароля</h1>
 
<form method="post">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p ><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
 
    <p ><button type="submit">Изменить пароль</button></p>
</form>
 
{% endblock %}

users/templates/users/profile.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Профиль</h1>
<a>Пользователь:{{ user.username }}</a>
<hr>Surname and Name: {{user.last_name}} {{user.first_name}}</hr> <hr>E-mail: {{user.email}}</hr>
<hr>Дата регистрации: {{user.date_joined}}</hr>

<hr class="first"> Добавленные альбомы:</hr>
{%for post in album.writer.username %}
<p class="first"> Добавленные альбомы: {{post}}
{%endfor%}
<hr></hr>
<form method="post">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p ><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
</form>
<form action="profile-update">
    <input type="submit" value="Сохранить" />
</form>
<hr ><a href="{% url 'users:password_change' %}">Сменить пароль</a></hr>
{% endblock %}

users/templates/users/profile_update.html
{% extends 'base_generic.html' %}
 
{% block content %}
<h1>Профиль успешно изменен!</h1>
 
<p >Вы успешно изменили профиль. <a href="{% url 'users:profile' %}">Вернуться в профиль.</a></p>
{% endblock %}

users/templates/users/register.html
{% extends 'base_generic.html' %}
 
{% block content %}
<h1>Регистрация</h1>
 
<form method="post">
    {% csrf_token %}
<input type="hidden" name="next" value="{{ next }}" />
    {{ form.as_p }}
    <p ><button type="submit">Регистрация</button></p>
</form>
 
{% endblock %}

users/templates/users/register_done.html
{% extends 'base_generic.html' %}
 
{% block content %}
<h1>Добро пожаловать!</h1>
 
<p >Вы успешно зарегистрировались на сайте! Для входа в систему необходимо авторизоваться по этой <a href="{% url 'users:login' %}">ссылке</a>
</p>
{% endblock %}